FROM app/spark-scala-env:latest

WORKDIR /app

# Pre-install base libraries
ADD build.sbt /app/
ADD project/plugins.sbt /app/project/
ADD src/. /app/src/

ADD NASA_access_log_Jul95.gz /app/
RUN ls -ltr
RUN chmod 777 /app/NASA_access_log_Jul95.gz
RUN sbt update

RUN sbt clean assembly